export const FetchConst = {
    SAVE_INITIAL_DATA: "SAVE INITIAL DATA",
    CLEAR_ALL_DATA: "CLEAR ALL DATA",
    SAVE_SEARCHED_PARKS: "SAVE SEARCHED PARKS",
    SAVE_SEARCHED_DRIVERS: "SAVE SEARCHED DRIVERS",
    SAVE_PARK_MEMBERS: "SAVE PARK MEMBERS"
}